# errors handling is here


class TrackbackErrors(object):
    def __init__(self): pass

    def check_errors(self, code_error):
        code_error_list = {
            "00000000": "Операция успешно завершена.",
            "00000001": "Ошибка аутентификации.",
            "00000002": "Ошибка во взаимосвязи.",
            "00000003": "Внешняя ошибка.",
            "00000004": "Внутренняя ошибка сервера.",
            "00000005": "Превышен таймаут на выполнение метода.",
            "00000006": "Ошибка Web.",
            "00000007": "Некорректные параметры."
        }
        print(code_error_list[code_error])